// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "billing-engine/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RepaymentServiceInterface is an autogenerated mock type for the RepaymentServiceInterface type
type RepaymentServiceInterface struct {
	mock.Mock
}

// ProcessRepayment provides a mock function with given fields: ctx, req
func (_m *RepaymentServiceInterface) ProcessRepayment(ctx context.Context, req *models.RepaymentRequest) (*models.RepaymentResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ProcessRepayment")
	}

	var r0 *models.RepaymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.RepaymentRequest) (*models.RepaymentResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.RepaymentRequest) *models.RepaymentResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RepaymentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.RepaymentRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepaymentServiceInterface creates a new instance of RepaymentServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepaymentServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepaymentServiceInterface {
	mock := &RepaymentServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
