// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "billing-engine/models"
)

// DisbursementServiceInterface is an autogenerated mock type for the DisbursementServiceInterface type
type DisbursementServiceInterface struct {
	mock.Mock
}

// CreateDisbursement provides a mock function with given fields: ctx, req
func (_m *DisbursementServiceInterface) CreateDisbursement(ctx context.Context, req *models.DisbursementRequest) (*models.DisbursementResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateDisbursement")
	}

	var r0 *models.DisbursementResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.DisbursementRequest) (*models.DisbursementResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.DisbursementRequest) *models.DisbursementResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DisbursementResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.DisbursementRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDisbursementServiceInterface creates a new instance of DisbursementServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDisbursementServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *DisbursementServiceInterface {
	mock := &DisbursementServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
