// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "billing-engine/models"
)

// LoanQueryMySQLRepositoryInterface is an autogenerated mock type for the LoanQueryMySQLRepositoryInterface type
type LoanQueryMySQLRepositoryInterface struct {
	mock.Mock
}

// GetLoanSummaryByLoanID provides a mock function with given fields: ctx, loanID
func (_m *LoanQueryMySQLRepositoryInterface) GetLoanSummaryByLoanID(ctx context.Context, loanID string) (*models.LoanSummary, error) {
	ret := _m.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for GetLoanSummaryByLoanID")
	}

	var r0 *models.LoanSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.LoanSummary, error)); ok {
		return rf(ctx, loanID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.LoanSummary); ok {
		r0 = rf(ctx, loanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LoanSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOverduePaymentSchedulesByLoanID provides a mock function with given fields: ctx, loanID
func (_m *LoanQueryMySQLRepositoryInterface) GetOverduePaymentSchedulesByLoanID(ctx context.Context, loanID string) ([]*models.PaymentSchedule, error) {
	ret := _m.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for GetOverduePaymentSchedulesByLoanID")
	}

	var r0 []*models.PaymentSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.PaymentSchedule, error)); ok {
		return rf(ctx, loanID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.PaymentSchedule); ok {
		r0 = rf(ctx, loanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PaymentSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaidPaymentSchedulesByLoanID provides a mock function with given fields: ctx, loanID
func (_m *LoanQueryMySQLRepositoryInterface) GetPaidPaymentSchedulesByLoanID(ctx context.Context, loanID string) ([]*models.PaymentSchedule, error) {
	ret := _m.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for GetPaidPaymentSchedulesByLoanID")
	}

	var r0 []*models.PaymentSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.PaymentSchedule, error)); ok {
		return rf(ctx, loanID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.PaymentSchedule); ok {
		r0 = rf(ctx, loanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PaymentSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentSchedulesByLoanID provides a mock function with given fields: ctx, loanID
func (_m *LoanQueryMySQLRepositoryInterface) GetPaymentSchedulesByLoanID(ctx context.Context, loanID string) ([]*models.PaymentSchedule, error) {
	ret := _m.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentSchedulesByLoanID")
	}

	var r0 []*models.PaymentSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.PaymentSchedule, error)); ok {
		return rf(ctx, loanID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.PaymentSchedule); ok {
		r0 = rf(ctx, loanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PaymentSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingPaymentSchedulesByLoanID provides a mock function with given fields: ctx, loanID
func (_m *LoanQueryMySQLRepositoryInterface) GetPendingPaymentSchedulesByLoanID(ctx context.Context, loanID string) ([]*models.PaymentSchedule, error) {
	ret := _m.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingPaymentSchedulesByLoanID")
	}

	var r0 []*models.PaymentSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.PaymentSchedule, error)); ok {
		return rf(ctx, loanID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.PaymentSchedule); ok {
		r0 = rf(ctx, loanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PaymentSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLoanQueryMySQLRepositoryInterface creates a new instance of LoanQueryMySQLRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoanQueryMySQLRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoanQueryMySQLRepositoryInterface {
	mock := &LoanQueryMySQLRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
